### ISSUE TITLE
Full Course Listing with Sorting and Filtering

### ISSUE THREAD

**Issue by geeksfn** [cesbrandt/canvas-javascript-courseFullListFilter#1]
Hi Christopher, 

I tried sending you a message on the Canvas community but could not do it there.

First of all, you did an excellent job with the Java script for the Full Course listing.

I wanted to ask how I can add include[]=total_students in the script? I am completely aware that this will increase the load time. Also, how to list the enrollment less course as well?

Thanks,
Faizan

**Comment by cesbrandt** [comment]
Because it's an option under the API to be included in the existing calls, it actually wouldn't take any significant increase in load time to do this, just modification of the code.

**Note**: Now, I'm just going to throw this out there now, I've not tested these instructions (I'm currently unable to do so), but they should work following the logic of the API documentation.

1. So, the first edit needed would be to the API call initiated on [line 158](https://github.com/cesbrandt/canvas-javascript-courseFullListFilter/blob/e80fa423d50197c317f34f19fe8e972a63a20910/canvasCourseFullListFilter.user.js#L158). The array that is the value for `.include` needs to be expanded to include the `total_students` value:
`callAPI([view, viewID, 'courses'], 1, [{include: ['teachers', 'total_students']}], oncomplete);`
2. Next will be adding it to the table rows on [line 227](https://github.com/cesbrandt/canvas-javascript-courseFullListFilter/blob/e80fa423d50197c317f34f19fe8e972a63a20910/canvasCourseFullListFilter.user.js#L227). Simply add a new table data element (`<td></td>`) where in the row you want it displayed that calls the `total_students` value from the `course` object:
`'<td>' + course.total_students + '</td>' +`
3. Lastly, you will need to add the column header to the table row containing the rest of the table headers (make sure the position matches that of the previous step) [line 268](https://github.com/cesbrandt/canvas-javascript-courseFullListFilter/blob/e80fa423d50197c317f34f19fe8e972a63a20910/canvasCourseFullListFilter.user.js#L268):
`'<th>Student Count</th>' +`

I don't think I missed anything, but I can't promise I didn't, I'm just torn between too many things right now to be sure. Just let me know if it doesn't work and I'll take a closer look when I have some time this evening. ^^'

**Comment by geeksfn** [comment]
It worked fine! I can see everything I need. Thanks a lot! Your prompt response is highly appreciated.

**Comment by cesbrandt** [comment]
I'm afraid that was just luck. Normally I'm not able to check this inbox so early, but I'm glad it's working for you. :)

I'm going to close this thread. Feel free to reopen it if you have any problems with this, or a new one for something else. ^^

**Comment by geeksfn** [comment]
Hi Chris, sorry for bothering you again.

For some reason, I am unable to list _all_ the courses...

I checked the ones that are getting listed and the ones that are not, they have completely identical course details...

**Comment by geeksfn** [comment]
it looks like it cannot be reopened.. ^^

**Comment by cesbrandt** [comment]
I will be able to take a look into it on Monday. I'm afraid I'm away from my computer for the weekend. :(

**Comment by cesbrandt** [comment]
@geeksfn, I made the modifications to the script exactly as I provided and the count is working just fine for me. Have you made any other modifications to the script?

**Comment by geeksfn** [comment]
No, I did not make any other changes. When I filter without the script for the sub account, it gives me 65 courses however when I use the script it gives me only 41.

**Comment by cesbrandt** [comment]
What is your setup? I've tested in Chrome 60 and Firefox 54 on Win 10, both of which worked as expected. with our Instructure-hosted installation.

We literally just made our live shells for the next term, so I tested in several of the accounts used and each produced the exact list that the default UI produced with the correct information. If it was going to show inaccurate listings, I would assume it would be with them due to their being the newest shells made, thus maybe not cached in the API, yet. :S

**Comment by geeksfn** [comment]
I have tried on both Chrome 60 and Firefox 64 on Win 10. You are right it may not be cached in the API. Thanks for all your help. :) 👍

**Comment by cesbrandt** [comment]
I could be mistaken, but my experience is that caching updates rather frequently.

If it's not showing everything there and you've made no other modifications, I'm afraid I am not able to offer additional support. The script with the supplied modification instructions is working as expected everywhere I test it (I pulled it up in Safari since my last message).

I wish I could offer more. :(
